from manim import *
class Area(Scene):
   def construct(self):
      text1 = Text("Area entre curvas")
      self.play(Write(text1),run_time=2)
      self.wait(2)
      fx= MathTex(r" f(x)=4x - x^2 -1",r" f(x)=4x - x^2 -1","f(x)")
      gx= MathTex(r" g(x)=x^2 -1",r" g(x)=x^2 -1","g(x)")
      fx[0].move_to(0.5*UP)
      gx[0].move_to(0.5*DOWN)
      text2 = Text("Area entre curvas",font_size=40)
      text2.move_to(3*UL + LEFT)
      self.play(Transform(text1,text2),run_play=3)
      self.play(Write(fx[0]),run_play=3)
      self.play(Write(gx[0]),run_play=3)
      self.wait(2)
      fx[1].move_to(3*UP + 0.5*RIGHT)
      gx[1].move_to(3*UP + 4.5*RIGHT)
      self.play(Transform(fx[0],fx[1]),Transform(gx[0],gx[1]),run_play=3)
      imagen0=ImageMobject("Area_ManimCE_v0.18.0.png").move_to(0.5*DOWN)
      imagen0.height=5.7
      self.add(imagen0)
      self.wait(3)
      imagen1=imagen0.copy()
      imagen1.height=4.5
      imagen1.move_to(DOWN + 3*LEFT)
      fx[2].move_to(2*DOWN + 0.3*LEFT)
      fx[2].height=0.5
      gx[2].move_to(UP + LEFT)
      gx[2].height=0.5
      self.play(Transform(imagen0,imagen1),Transform(fx[1],fx[2]),Transform(gx[1],gx[2],run_play=3))
      self.wait(3)
      texto=Text("Hallamos la interseccion entre las funciones",font_size=26)
      resu=MathTex(r"f(x)=g(x)",r"4x - x^2 -1 = x^2 -1",r"x(x-2)=0","x=0,x=2",font_size=34)
      texto.move_to(2*UP + 2.5*RIGHT)
      resu[0].move_to(1.3*UP + 2.5*RIGHT)
      resu[1].move_to(1.3*UP + 2.5*RIGHT)
      resu[2].move_to(1.3*UP + 2.5*RIGHT)
      resu[3].move_to(1.3*UP + 2.5*RIGHT)
      self.play(Write(texto),run_play=4)
      self.wait()
      self.play(Write(resu[0]),run_play=4)
      self.wait()
      self.play(Transform(resu[0],resu[1]),run_play=4)
      self.wait(2)
      self.remove(resu[0])
      self.play(Transform(resu[1],resu[2]),run_play=4)
      self.wait(2)
      self.remove(resu[1])
      self.play(Transform(resu[2],resu[3]),run_play=4)
      self.wait(2)
      text2=Text("Hallamos el area",font_size=26)
      area=MathTex(r"\int_{0}^{2} (f(x)- g(x))dx + \int_{2}^{3} (g(x)- f(x))dx",
                   r"\int_{0}^{2} (f(x)- g(x))dx + \int_{2}^{3} (g(x)- f(x))dx",
                   r"\int_{0}^{2}((4x - x^2 -1)-(x^2 -1))dx + \int_{2}^{3}((x^2 -1)-(4x - x^2 -1))dx",
                   r"\int_{0}^{2}(4x - 2x^2)dx + \int_{2}^{3}(2x^2 -4x)dx",
                   r"2(\int_{0}^{2}(2x - x^2)dx + \int_{2}^{3}(x^2 -2x)dx)",
                   r"=2((x^2 -\frac{x^3}{3})|\begin{matrix} 2 \\0 \end{matrix} + (\frac{x^3}{3} -x^2)|\begin{matrix} 3 \\2 \end{matrix} )",
                   r"\int_{b}^{a}f(x)dx=F(x)|\begin{matrix} a \\ b \end{matrix} = F(a)-F(b)",
                   r"2((2^2 -\frac{2^3}{3})-(0^2 -\frac{0^3}{3})+ (\frac{3^3}{3} -3^2)-(\frac{2^3}{3} -2^2))",
                   r"2((4 -\frac{8}{3})+(\frac{27}{3} -9)-(\frac{8}{3} -4))",
                   r"2((4 -\frac{8}{3})-(\frac{8}{3} -4))",
                   r"2((8 -\frac{16}{3}))=2(\frac{24}{3} -\frac{16}{3}))=\frac{16}{3}",
                   r"\frac{16}{3} u^{2}",
                   font_size=34)
      text2.move_to(0.5*UP + 2.5*RIGHT)
      area[0].move_to(0.8*DOWN +2.7*RIGHT)
      area[1].move_to(2*UP + 3*LEFT)
      area[2].move_to(2*UP + 1.8*LEFT)
      area[3].move_to(2*UP + 2.5*LEFT)
      area[4].move_to(2*UP + 2.5*LEFT)
      area[5].move_to(2*UP + 3*RIGHT)
      recordar=Text("Usamos el segundo teorema fundamental del calculo",font_size=18)
      recordar.move_to(UP + 3*RIGHT)
      area[6].move_to(3*RIGHT)
      area[7].move_to(DOWN + 3.1*RIGHT)
      area[8].move_to(DOWN + 3.1*RIGHT)
      area[9].move_to(DOWN + 3.1*RIGHT)
      area[10].move_to(DOWN + 3.1*RIGHT)
      area[11].move_to(2*DOWN + 3.1*RIGHT)
      self.play(Write(text2))
      self.play(Write(area[0]))
      self.wait(2)
      self.play(Transform(area[0],area[1]),Transform(resu,area[1]),Transform(text2,area[1]),Transform(texto,area[1]))
      self.wait(2)
      self.remove(resu,texto,area[0],text2)
      self.play(Transform(area[1],area[2]))
      self.wait(2)
      self.remove(area[1])
      self.play(Transform(area[2],area[3]))
      self.wait(2)
      self.remove(area[2])
      self.play(Transform(area[3],area[4]))
      self.wait(2)
      self.play(Write(area[5]))
      self.wait(2)
      self.play(Write(recordar))
      self.wait(2)
      self.play(Write(area[6]))
      self.wait(2)
      self.play(Write(area[7]))
      self.wait(2)
      self.play(Transform(area[7],area[8]))
      self.wait(2)
      self.remove(area[7])
      self.play(Transform(area[8],area[9]))
      self.wait(2)
      self.remove(area[8])
      self.play(Transform(area[9],area[10]))
      self.wait(2)
      self.play(Write(area[11]))
      self.wait(2)